# Generated by Django 5.0.6 on 2026-08-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name'], 'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='کد شهر'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='کد استان'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام استان'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'name'], name='cities_provinc_e3ddcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_city_per_province'),
        ),
    ]
