# Generated by Django 5.0.6 on 2026-08-25 08:57

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=core.utils.generate_invoice_number, max_length=20, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/invoices/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
